-- CRIAR BANCO DE DADOS
CREATE DATABASE GREENHOUSE;
GO

-- USAR BANCO DE DADOS
USE GREENHOUSE;
GO

-- CRIAR TABELA PLANTS
CREATE TABLE PLANTS (
    PLANT_NAME VARCHAR(30) NOT NULL PRIMARY KEY,
    SENSOR_VALUE FLOAT NULL,
    SENSOR_EVENT DATETIME NOT NULL 
        DEFAULT GETDATE()
);
GO

-- VISUALIZAR TODAS AS OCORRÊNCIAS EM PLANTS
SELECT * FROM PLANTS;
GO

SELECT PLANT_NAME, SENSOR_VALUE, SENSOR_EVENT FROM PLANTS;
GO

-- INSERIR UM REGISTRO
INSERT INTO PLANTS (PLANT_NAME, SENSOR_VALUE)
VALUES ('ROSA', 0.2319);
GO

-- INSERIR MÚLTIPLOS REGISTROS
INSERT INTO PLANTS (PLANT_NAME, SENSOR_VALUE)
VALUES 
    ('CACTUS', 0.2411),
    ('GIRASSOL', 0.3112),
    ('ORQUÍDEA', 0.4102),
    ('LÍRIO', 0.5566);
GO
