// <auto-generated />
using System;
using Greenhouse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenHouse.Migrations
{
    [DbContext(typeof(GreenhouseContext))]
    partial class GreenhouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Greenhouse.Models.Plant", b =>
                {
                    b.Property<string>("Plant_Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Sensor_Event")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Sensor_Value")
                        .HasColumnType("real");

                    b.HasKey("Plant_Name");

                    b.ToTable("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
